# Generated by Django 4.2.23 on 2025-07-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_advertisement',
            field=models.BooleanField(default=False),
        ),
    ]
