# Generated by Django 4.2.23 on 2025-07-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_uploadedfile_is_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تأیید توسط ادمین'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='is_advertisement',
            field=models.BooleanField(default=False, verbose_name='تبلیغ برای ادمین'),
        ),
    ]
